/**
 * ينشئ Base تجريبي (Preview/Sandbox) منفصل عن الإنتاج على Airtable.
 * التشغيل: npm run setup:airtable-preview
 *
 * إذا فشل إنشاء Base تلقائياً:
 * 1) أنشئ Base يدوياً في Airtable باسم "TaalofDB Preview (Sandbox)"
 * 2) انسخ Base ID (يبدأ بـ app...)
 * 3) AIRTABLE_PREVIEW_BASE_ID=appXXX npm run setup:airtable-preview
 */

import fs from 'fs';
import path from 'path';
import { loadEnvFiles } from './load-env';
import {
  createPreviewBase,
  listBases,
  provisionTaalofTables,
  resolveWorkspaceForBase,
} from './airtable-provision';

loadEnvFiles();

const PREVIEW_BASE_NAME =
  process.env.AIRTABLE_PREVIEW_BASE_NAME?.trim() || 'TaalofDB Preview (Sandbox)';

function manualBaseInstructions() {
  console.log('\n📋 إنشاء Base يدوياً (دقيقتان):');
  console.log('   1) افتح https://airtable.com');
  console.log('   2) أنشئ Base جديد باسم:');
  console.log(`      ${PREVIEW_BASE_NAME}`);
  console.log('   3) من الرابط أو API docs انسخ Base ID (appXXXXXXXX)');
  console.log('   4) شغّل:');
  console.log('      AIRTABLE_PREVIEW_BASE_ID=appXXX npm run setup:airtable-preview\n');
  console.log('أو أضِف صلاحية schema.bases:write + workspace access للتوكن');
  console.log('وعيّن AIRTABLE_WORKSPACE_ID=wspXXXXXXXX في .env.local\n');
}

async function seedPreviewRecords(apiKey: string, baseId: string) {
  for (const [table, fields] of [
    [
      'Students',
      {
        Name: 'طفل تجريبي — Preview',
        Status: 'sandbox',
        Notes: 'سجل تجريبي — لا يُستخدم في الإنتاج',
      },
    ],
    [
      'Specialists',
      {
        Name: 'أخصائي تجريبي',
        Email: 'preview-specialist@taaluf.local',
        Specialty: 'sandbox',
      },
    ],
  ] as const) {
    await fetch(
      `https://api.airtable.com/v0/${baseId}/${encodeURIComponent(table)}`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ records: [{ fields }] }),
      }
    );
  }
}

function writePreviewEnvFile(previewBaseId: string, productionBaseId: string) {
  const outPath = path.join(process.cwd(), '.airtable-preview.env');
  const body = `# Generated by npm run setup:airtable-preview — do NOT commit
# Copy these to Vercel → Environment Variables → Preview

AIRTABLE_BASE_ID=${previewBaseId}
AIRTABLE_BASE_NAME=${PREVIEW_BASE_NAME}
AIRTABLE_PRODUCTION_BASE_ID=${productionBaseId}
NEXT_PUBLIC_SHOW_ENV_BANNER=true
ALLOW_DEMO_USERS=true
TAALUF_PILOT_MODE=true
NEXT_PUBLIC_TAALUF_PILOT_MODE=true
PAYMENTS_DISABLED=true
NEXT_PUBLIC_PAYMENTS_DISABLED=true
`;
  fs.writeFileSync(outPath, body, 'utf8');
  return outPath;
}

async function main() {
  const apiKey = process.env.AIRTABLE_API_KEY || '';
  const productionBaseId =
    process.env.AIRTABLE_PRODUCTION_BASE_ID?.trim() ||
    process.env.AIRTABLE_BASE_ID ||
    '';

  console.log('\n━━━ إنشاء Base تجريبي Airtable (Preview) ━━━\n');

  if (!apiKey) {
    console.log('❌ عيّن AIRTABLE_API_KEY في .env.local\n');
    process.exit(1);
  }
  if (!productionBaseId) {
    console.log('❌ عيّن AIRTABLE_BASE_ID (الإنتاج) في .env.local\n');
    process.exit(1);
  }

  let previewBaseId = process.env.AIRTABLE_PREVIEW_BASE_ID?.trim() || '';

  if (!previewBaseId) {
    const bases = await listBases(apiKey);
    const existing = bases.find((b) => b.name === PREVIEW_BASE_NAME);
    if (existing) {
      previewBaseId = existing.id;
      console.log(`⏭  Base موجود: ${PREVIEW_BASE_NAME} (${previewBaseId})`);
    }
  }

  if (!previewBaseId) {
    let workspaceId = process.env.AIRTABLE_WORKSPACE_ID?.trim() || '';
    if (!workspaceId) {
      workspaceId =
        (await resolveWorkspaceForBase(apiKey, productionBaseId)) || '';
      if (workspaceId) {
        console.log(`ℹ️  workspace من Base الإنتاج: ${workspaceId}`);
      }
    }
    if (!workspaceId) {
      console.log('⚠️  AIRTABLE_WORKSPACE_ID غير مضبوط — لا يمكن الإنشاء التلقائي.');
      manualBaseInstructions();
      process.exit(1);
    }
    try {
      console.log(`🆕 إنشاء Base: ${PREVIEW_BASE_NAME}`);
      previewBaseId = await createPreviewBase(apiKey, workspaceId, PREVIEW_BASE_NAME);
      console.log(`✅ Base ID: ${previewBaseId}`);
    } catch (err) {
      console.log(
        `❌ ${err instanceof Error ? err.message : err}`
      );
      manualBaseInstructions();
      process.exit(1);
    }
  }

  console.log('\n→ إنشاء/تحديث الجداول…\n');
  await provisionTaalofTables(apiKey, previewBaseId);

  console.log('\n→ إضافة سجل تجريبي…');
  try {
    await seedPreviewRecords(apiKey, previewBaseId);
    console.log('✅ سجل تجريبي');
  } catch {
    console.log('⚠️  تعذر إضافة السجل التجريبي (اختياري)');
  }

  const envFile = writePreviewEnvFile(previewBaseId, productionBaseId);

  console.log('\n—— تم ——\n');
  console.log(`Preview Base ID:  ${previewBaseId}`);
  console.log(`Production Base ID: ${productionBaseId}`);
  console.log(`\nملف الإعداد: ${envFile}`);
  console.log('\nVercel → Preview environment:');
  console.log(`  AIRTABLE_BASE_ID = ${previewBaseId}`);
  console.log(`  AIRTABLE_PRODUCTION_BASE_ID = ${productionBaseId}`);
  console.log('\nVercel → Production environment:');
  console.log(`  AIRTABLE_BASE_ID = ${productionBaseId}`);
  console.log(`  AIRTABLE_PRODUCTION_BASE_ID = ${productionBaseId}`);
  console.log('');
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
